# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "exec_sandbox"
  s.version = "0.2.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Victor Costan"]
  s.date = "2014-02-06"
  s.description = "Temporary users and groups, rlimits"
  s.email = "costan@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".project",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "exec_sandbox.gemspec",
    "lib/exec_sandbox.rb",
    "lib/exec_sandbox/sandbox.rb",
    "lib/exec_sandbox/spawn.rb",
    "lib/exec_sandbox/users.rb",
    "lib/exec_sandbox/wait4.rb",
    "spec/exec_sandbox/sandbox_spec.rb",
    "spec/exec_sandbox/spawn_spec.rb",
    "spec/exec_sandbox/users_spec.rb",
    "spec/exec_sandbox/wait4_spec.rb",
    "spec/fixtures/buffer.rb",
    "spec/fixtures/churn.rb",
    "spec/fixtures/count.rb",
    "spec/fixtures/duplicate.rb",
    "spec/fixtures/exit_arg.rb",
    "spec/fixtures/fork.rb",
    "spec/fixtures/pwd.rb",
    "spec/fixtures/write_arg.rb",
    "spec/spec_helper.rb",
    "spec/support/code_fixture.rb"
  ]
  s.homepage = "http://github.com/pwnall/exec_sandbox"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Run foreign binaries using POSIX sandboxing features"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, [">= 1.9.3"])
      s.add_development_dependency(%q<rdoc>, [">= 3.10"])
      s.add_development_dependency(%q<rspec>, [">= 2.14.1"])
      s.add_development_dependency(%q<yard>, [">= 0.8.7.3"])
      s.add_development_dependency(%q<yard-rspec>, [">= 0.1"])
      s.add_development_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<ffi>, [">= 1.9.3"])
      s.add_dependency(%q<rdoc>, [">= 3.10"])
      s.add_dependency(%q<rspec>, [">= 2.14.1"])
      s.add_dependency(%q<yard>, [">= 0.8.7.3"])
      s.add_dependency(%q<yard-rspec>, [">= 0.1"])
      s.add_dependency(%q<bundler>, [">= 1.3.5"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<ffi>, [">= 1.9.3"])
    s.add_dependency(%q<rdoc>, [">= 3.10"])
    s.add_dependency(%q<rspec>, [">= 2.14.1"])
    s.add_dependency(%q<yard>, [">= 0.8.7.3"])
    s.add_dependency(%q<yard-rspec>, [">= 0.1"])
    s.add_dependency(%q<bundler>, [">= 1.3.5"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

